# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: versions_check
    steps: 
    - script: |
        mvn -version
        git --version
        java -version
        kubectl --version
        mysql --version
    - bash: echo "This is New test" >> test.txt
    - bash: |
        pwd
        ls -ltr

    - task: CopyFiles@2
      inputs:
        SourceFolder: '.'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
